In [1]:
import pandas as pd
import numpy as np
import nltk
# The NLTK data package includes a pre-trained Punkt tokenizer for English.
# punkt had to be manually downloaded using the command below
# same with stopwords
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
df = pd.read_csv('/kaggle/input/translated-data-english/translated_data_english.tsv', sep='\t')

In [3]:
df.head()

id        label                                          statement  \
0  10540.json    half-true  When did the decline of coal start? It started...   
1    324.json  mostly-true  Hillary Clinton agrees with John McCain "by vo...   
2   1123.json        false  Health care reform legislation is likely to ma...   
3   9028.json    half-true  The economic turnaround started at the end of ...   
4  12465.json         true  The Chicago Bears have had more starting quart...   

                             subjects         speaker  \
0  energy,history,job-accomplishments  scott-surovell   
1                      foreign-policy    barack-obama   
2                         health-care    blog-posting   
3                        economy,jobs   charlie-crist   
4                           education       robin-vos   

            speaker_job_title state_info party_affilation  count_1  count_2  \
0              State delegate   Virginia         democrat      0.0      0.0   
1                   President   Illinois         democrat     70.0     71.0   
2                         NaN        NaN             none      7.0     19.0   
3                         NaN    Florida         democrat     15.0      9.0   
4  Wisconsin Assembly speaker  Wisconsin       republican      0.0      3.0   

   count_3  count_4  count_5                    context  \
0      1.0      1.0      0.0            a floor speech.   
1    160.0    163.0      9.0                     Denver   
2      3.0      5.0     44.0             a news release   
3     20.0     19.0      2.0        an interview on CNN   
4      2.0      5.0      1.0  a an online opinion-piece   

                        statement_removedpunctuation  \
0  When did the decline of coal start It started ...   
1  Hillary Clinton agrees with John McCain by vot...   
2  Health care reform legislation is likely to ma...   
3  The economic turnaround started at the end of ...   
4  The Chicago Bears have had more starting quart...   

                                  nepali_translation  \
0  कोइलाको पतन कहिले सुरु भयो यो प्राकृतिक ग्यास ...   
1  हिलारी क्लिन्टनले जर्ज बुशलाई इरानमा शंकाको फा...   
2  स्वास्थ्य हेरचाह सुधार कानूनले नि: शुल्क लिंग ...   
3  मेरो कार्यकालको अन्त्यमा आर्थिक परिवर्तन सुरु भयो   
4  शिकागो बियर्सले विगत दुई दशकहरूमा बर्खास्त गरि...   

                                 english_translation  
0  When did the decline of coal begin? It began w...  
1  Hillary Clinton agreed with John McCain by vot...  
2  Health care reform legislation is likely to ma...  
3  Towards the end of my tenure, the economic tra...  
4  The Chicago Bears have had more starting quart...

In [4]:
df['english_translation'] = df['english_translation'].str.lower()

In [5]:
df.head()

id        label                                          statement  \
0  10540.json    half-true  When did the decline of coal start? It started...   
1    324.json  mostly-true  Hillary Clinton agrees with John McCain "by vo...   
2   1123.json        false  Health care reform legislation is likely to ma...   
3   9028.json    half-true  The economic turnaround started at the end of ...   
4  12465.json         true  The Chicago Bears have had more starting quart...   

                             subjects         speaker  \
0  energy,history,job-accomplishments  scott-surovell   
1                      foreign-policy    barack-obama   
2                         health-care    blog-posting   
3                        economy,jobs   charlie-crist   
4                           education       robin-vos   

            speaker_job_title state_info party_affilation  count_1  count_2  \
0              State delegate   Virginia         democrat      0.0      0.0   
1                   President   Illinois         democrat     70.0     71.0   
2                         NaN        NaN             none      7.0     19.0   
3                         NaN    Florida         democrat     15.0      9.0   
4  Wisconsin Assembly speaker  Wisconsin       republican      0.0      3.0   

   count_3  count_4  count_5                    context  \
0      1.0      1.0      0.0            a floor speech.   
1    160.0    163.0      9.0                     Denver   
2      3.0      5.0     44.0             a news release   
3     20.0     19.0      2.0        an interview on CNN   
4      2.0      5.0      1.0  a an online opinion-piece   

                        statement_removedpunctuation  \
0  When did the decline of coal start It started ...   
1  Hillary Clinton agrees with John McCain by vot...   
2  Health care reform legislation is likely to ma...   
3  The economic turnaround started at the end of ...   
4  The Chicago Bears have had more starting quart...   

                                  nepali_translation  \
0  कोइलाको पतन कहिले सुरु भयो यो प्राकृतिक ग्यास ...   
1  हिलारी क्लिन्टनले जर्ज बुशलाई इरानमा शंकाको फा...   
2  स्वास्थ्य हेरचाह सुधार कानूनले नि: शुल्क लिंग ...   
3  मेरो कार्यकालको अन्त्यमा आर्थिक परिवर्तन सुरु भयो   
4  शिकागो बियर्सले विगत दुई दशकहरूमा बर्खास्त गरि...   

                                 english_translation  
0  when did the decline of coal begin? it began w...  
1  hillary clinton agreed with john mccain by vot...  
2  health care reform legislation is likely to ma...  
3  towards the end of my tenure, the economic tra...  
4  the chicago bears have had more starting quart...

In [6]:
import string
def removepunctuation(sentence):
   new_text = sentence.replace("—", " ") # "—" in the text was not equivalent to "-" so we replcaed "—" with a space
   print 
  #iterate over every single character to see if it is a punctuation or not, and then concatenate them using "join"
   punctuationfree="".join([i for i in new_text if i not in string.punctuation])
   return punctuationfree

In [7]:
df["statement_removedpunctuation"] = df['english_translation'].apply(lambda x : removepunctuation(x))

In [8]:
df.head()

id        label                                          statement  \
0  10540.json    half-true  When did the decline of coal start? It started...   
1    324.json  mostly-true  Hillary Clinton agrees with John McCain "by vo...   
2   1123.json        false  Health care reform legislation is likely to ma...   
3   9028.json    half-true  The economic turnaround started at the end of ...   
4  12465.json         true  The Chicago Bears have had more starting quart...   

                             subjects         speaker  \
0  energy,history,job-accomplishments  scott-surovell   
1                      foreign-policy    barack-obama   
2                         health-care    blog-posting   
3                        economy,jobs   charlie-crist   
4                           education       robin-vos   

            speaker_job_title state_info party_affilation  count_1  count_2  \
0              State delegate   Virginia         democrat      0.0      0.0   
1                   President   Illinois         democrat     70.0     71.0   
2                         NaN        NaN             none      7.0     19.0   
3                         NaN    Florida         democrat     15.0      9.0   
4  Wisconsin Assembly speaker  Wisconsin       republican      0.0      3.0   

   count_3  count_4  count_5                    context  \
0      1.0      1.0      0.0            a floor speech.   
1    160.0    163.0      9.0                     Denver   
2      3.0      5.0     44.0             a news release   
3     20.0     19.0      2.0        an interview on CNN   
4      2.0      5.0      1.0  a an online opinion-piece   

                        statement_removedpunctuation  \
0  when did the decline of coal begin it began wi...   
1  hillary clinton agreed with john mccain by vot...   
2  health care reform legislation is likely to ma...   
3  towards the end of my tenure the economic tran...   
4  the chicago bears have had more starting quart...   

                                  nepali_translation  \
0  कोइलाको पतन कहिले सुरु भयो यो प्राकृतिक ग्यास ...   
1  हिलारी क्लिन्टनले जर्ज बुशलाई इरानमा शंकाको फा...   
2  स्वास्थ्य हेरचाह सुधार कानूनले नि: शुल्क लिंग ...   
3  मेरो कार्यकालको अन्त्यमा आर्थिक परिवर्तन सुरु भयो   
4  शिकागो बियर्सले विगत दुई दशकहरूमा बर्खास्त गरि...   

                                 english_translation  
0  when did the decline of coal begin? it began w...  
1  hillary clinton agreed with john mccain by vot...  
2  health care reform legislation is likely to ma...  
3  towards the end of my tenure, the economic tra...  
4  the chicago bears have had more starting quart...

In [9]:
df["english_translation_tokenized"] = df["statement_removedpunctuation"].apply(word_tokenize)

In [10]:
df["english_translation_tokenized"].iloc[7]

['however',
 'it',
 'took',
 'one',
 'hundred',
 'and',
 'ninetyfive',
 'million',
 'in',
 'oregon',
 'lottery',
 'funds',
 'for',
 'the',
 'port',
 'of',
 'newport',
 'to',
 'finally',
 'land',
 'the',
 'new',
 'noaa',
 'marine',
 'operations',
 'center',
 'in',
 'the',
 'pacific']

In [11]:
stop_words = stopwords.words('english')

In [12]:
def stopwordremoval(words):
    preprocessed_tokens = []
    for i in words:
        # Remove stopwords and empty strings while keeping words separated by space
        post_removal = [word for word in i.split() if word.lower() not in stop_words]
        filtered_string = " ".join(post_removal).strip()
        if filtered_string:
            preprocessed_tokens.append(filtered_string)
    # Combine the preprocessed tokens into a single string
    combined_string = " ".join(preprocessed_tokens)
    return combined_string

In [13]:
stopwordremoval(['however',
 'it',
 'took',
 'one',
 'hundred',
 'and',
 'ninetyfive',
 'million',
 'in',
 'oregon',
 'lottery',
 'funds',
 'for',
 'the',
 'port',
 'of',
 'newport',
 'to',
 'finally',
 'land',
 'the',
 'new',
 'noaa',
 'marine',
 'operations',
 'center',
 'in',
 'the',
 'pacific'])

'however took one hundred ninetyfive million oregon lottery funds port newport finally land new noaa marine operations center pacific'

In [14]:
df["english_translation_stopwords"] = df["english_translation_tokenized"].apply(stopwordremoval)

In [15]:
df.head()

id        label                                          statement  \
0  10540.json    half-true  When did the decline of coal start? It started...   
1    324.json  mostly-true  Hillary Clinton agrees with John McCain "by vo...   
2   1123.json        false  Health care reform legislation is likely to ma...   
3   9028.json    half-true  The economic turnaround started at the end of ...   
4  12465.json         true  The Chicago Bears have had more starting quart...   

                             subjects         speaker  \
0  energy,history,job-accomplishments  scott-surovell   
1                      foreign-policy    barack-obama   
2                         health-care    blog-posting   
3                        economy,jobs   charlie-crist   
4                           education       robin-vos   

            speaker_job_title state_info party_affilation  count_1  count_2  \
0              State delegate   Virginia         democrat      0.0      0.0   
1                   President   Illinois         democrat     70.0     71.0   
2                         NaN        NaN             none      7.0     19.0   
3                         NaN    Florida         democrat     15.0      9.0   
4  Wisconsin Assembly speaker  Wisconsin       republican      0.0      3.0   

   count_3  count_4  count_5                    context  \
0      1.0      1.0      0.0            a floor speech.   
1    160.0    163.0      9.0                     Denver   
2      3.0      5.0     44.0             a news release   
3     20.0     19.0      2.0        an interview on CNN   
4      2.0      5.0      1.0  a an online opinion-piece   

                        statement_removedpunctuation  \
0  when did the decline of coal begin it began wi...   
1  hillary clinton agreed with john mccain by vot...   
2  health care reform legislation is likely to ma...   
3  towards the end of my tenure the economic tran...   
4  the chicago bears have had more starting quart...   

                                  nepali_translation  \
0  कोइलाको पतन कहिले सुरु भयो यो प्राकृतिक ग्यास ...   
1  हिलारी क्लिन्टनले जर्ज बुशलाई इरानमा शंकाको फा...   
2  स्वास्थ्य हेरचाह सुधार कानूनले नि: शुल्क लिंग ...   
3  मेरो कार्यकालको अन्त्यमा आर्थिक परिवर्तन सुरु भयो   
4  शिकागो बियर्सले विगत दुई दशकहरूमा बर्खास्त गरि...   

                                 english_translation  \
0  when did the decline of coal begin? it began w...   
1  hillary clinton agreed with john mccain by vot...   
2  health care reform legislation is likely to ma...   
3  towards the end of my tenure, the economic tra...   
4  the chicago bears have had more starting quart...   

                       english_translation_tokenized  \
0  [when, did, the, decline, of, coal, begin, it,...   
1  [hillary, clinton, agreed, with, john, mccain,...   
2  [health, care, reform, legislation, is, likely...   
3  [towards, the, end, of, my, tenure, the, econo...   
4  [the, chicago, bears, have, had, more, startin...   

                       english_translation_stopwords  
0  decline coal begin began natural gas layoff be...  
1  hillary clinton agreed john mccain voting give...  
2  health care reform legislation likely mandate ...  
3   towards end tenure economic transformation began  
4  chicago bears starting quarterbacks past ten y...

In [16]:
df["statement_removedpunctuation"].iloc[200]

'over the past year more than twenty percent of americans have changed their minds about the war in afghanistan concluding that we shouldnt be there'

In [17]:
df["english_translation_stopwords"].iloc[200]

'past year twenty percent americans changed minds war afghanistan concluding shouldnt'

In [18]:
import spacy

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso

In [19]:
nlp = spacy.load("en_core_web_sm")


In [20]:
def lemmetization(text):
    doc = nlp(text)
    lemmetized = []
    for token in doc:
        lemmetized.append(token.lemma_)
    return " ".join(lemmetized)


In [21]:
df["preprocessed_english"] = df["english_translation_stopwords"].apply(lemmetization)

In [22]:
df.head()

id        label                                          statement  \
0  10540.json    half-true  When did the decline of coal start? It started...   
1    324.json  mostly-true  Hillary Clinton agrees with John McCain "by vo...   
2   1123.json        false  Health care reform legislation is likely to ma...   
3   9028.json    half-true  The economic turnaround started at the end of ...   
4  12465.json         true  The Chicago Bears have had more starting quart...   

                             subjects         speaker  \
0  energy,history,job-accomplishments  scott-surovell   
1                      foreign-policy    barack-obama   
2                         health-care    blog-posting   
3                        economy,jobs   charlie-crist   
4                           education       robin-vos   

            speaker_job_title state_info party_affilation  count_1  count_2  \
0              State delegate   Virginia         democrat      0.0      0.0   
1                   President   Illinois         democrat     70.0     71.0   
2                         NaN        NaN             none      7.0     19.0   
3                         NaN    Florida         democrat     15.0      9.0   
4  Wisconsin Assembly speaker  Wisconsin       republican      0.0      3.0   

   count_3  count_4  count_5                    context  \
0      1.0      1.0      0.0            a floor speech.   
1    160.0    163.0      9.0                     Denver   
2      3.0      5.0     44.0             a news release   
3     20.0     19.0      2.0        an interview on CNN   
4      2.0      5.0      1.0  a an online opinion-piece   

                        statement_removedpunctuation  \
0  when did the decline of coal begin it began wi...   
1  hillary clinton agreed with john mccain by vot...   
2  health care reform legislation is likely to ma...   
3  towards the end of my tenure the economic tran...   
4  the chicago bears have had more starting quart...   

                                  nepali_translation  \
0  कोइलाको पतन कहिले सुरु भयो यो प्राकृतिक ग्यास ...   
1  हिलारी क्लिन्टनले जर्ज बुशलाई इरानमा शंकाको फा...   
2  स्वास्थ्य हेरचाह सुधार कानूनले नि: शुल्क लिंग ...   
3  मेरो कार्यकालको अन्त्यमा आर्थिक परिवर्तन सुरु भयो   
4  शिकागो बियर्सले विगत दुई दशकहरूमा बर्खास्त गरि...   

                                 english_translation  \
0  when did the decline of coal begin? it began w...   
1  hillary clinton agreed with john mccain by vot...   
2  health care reform legislation is likely to ma...   
3  towards the end of my tenure, the economic tra...   
4  the chicago bears have had more starting quart...   

                       english_translation_tokenized  \
0  [when, did, the, decline, of, coal, begin, it,...   
1  [hillary, clinton, agreed, with, john, mccain,...   
2  [health, care, reform, legislation, is, likely...   
3  [towards, the, end, of, my, tenure, the, econo...   
4  [the, chicago, bears, have, had, more, startin...   

                       english_translation_stopwords  \
0  decline coal begin began natural gas layoff be...   
1  hillary clinton agreed john mccain voting give...   
2  health care reform legislation likely mandate ...   
3   towards end tenure economic transformation began   
4  chicago bears starting quarterbacks past ten y...   

                                preprocessed_english  
0  decline coal begin begin natural gas layoff be...  
1  hillary clinton agree john mccain voting give ...  
2  health care reform legislation likely mandate ...  
3   towards end tenure economic transformation begin  
4  chicago bear start quarterback past ten year t...

In [23]:
df["preprocessed_english"].iloc[0]

'decline coal begin begin natural gas layoff begin administration president george w bush'

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(lowercase = False)


In [25]:

X = vectorizer.fit_transform(df["preprocessed_english"])
# vectorizer.get_feature_names_out()


In [26]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
